on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build Release

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Run build
        run: cargo build --release --bin ghr
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: ghr_windows.exe
          path: target/release/ghr.exe
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Run build
        run: cargo build --release --bin ghr
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: ghr_mac
          path: target/release/ghr
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Run build
        run: cargo build --release --bin ghr
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: ghr_linux
          path: target/release/ghr
